### ISSUE TITLE
[UI Improvement] Add "Center" during route and map is not on route

### ISSUE THREAD

**Issue by WNYmathGuy** [costales/unav#4]
First I'd like to say, damn this is great mapping software!

Quick background, this is the type of problem I experienced as a n00b to UBports that made me think the Ubuntu Touch/UBports OS needed a universal back button. I was schooled on the error of my thinking by [that forum](https://forums.ubports.com/topic/3307/why-isnt-their-a-universal-jump-back-type-button-gesture).

During active navigation, I have many times accidentally touched an active area of the mapping display. I believe almost all if not all of those were from my thumb touching the top blue bar area while trying to put the mobile device into the holder in the vehicle. These accidental taps immediately try to give me options for what to do with the new point on the map that I touched and I'm no longer being shown the route I'm driving along. The only way I've found to get back to the routing to my intended destination was to close the app and restart the route. (_I do know I was doing it wrong, but this was how I experienced it._) Today when it happened at a stop sign when I fiddled with the volume buttons and dragged a finger on the map. I tried touching the compass needle icon, and that didn't really get me what I wanted. While writing this, I tried goofing around with things at my home. I discovered that icon of a circle in a circle in the top blue bar might be what I was supposed to touch, but it was not obvious to me. 

It seems that for a better UI experience for n00bs, a thin full-icon-sized "X" or ⨯ (cross-product character) in that pop-up menu for simply letting go of the newly touched point on the map and going back to what the app was doing right before it was touched would be a great addition.

**Comment by costales** [comment]
Hi :) Thanks for the feedback.
Maybe a button "Center" would be great.
I'll redone the title.
A hug :)

**Comment by dobey** [comment]
In this specific case for uNav, I'm not sure a "back" button is the answer; as you're not going to a new "page" in that case. I think this case is more a weird UX issue where the UI doesn't behave as it should, generally. I've noticed before when trying to tap the "target" icon in the top bar, that it ends up sending the tap to the map and repositioning, instead of triggering a location query to hardware as I'd expect. This is confusing/bad UX. While implementing some sort of history graph like a browser in uNav might achieve what you want, to "go back," it seems like the wrong solution to your specific issue.

I don't think "center" is necessarily right either. There should already be the "target" icon which should reposition the map to your current GPS location, but there are some issues with the UX there.

**Comment by costales** [comment]
It will be fixed in uNav 3

**Comment by costales** [comment]
Release this week :) Fixed!
