### ISSUE TITLE
Offline navigation via OSM Scout Server

### ISSUE THREAD

**Issue by jonnius** [costales/unav#8]
Would you be interested in letting unav use the OSM Scout Server for offline navigation in uNav? If so I would include Mapnik in OSM Scout Server to provide the map tiles.

**Comment by jonnius** [comment]
@rinigus FYI

**Comment by costales** [comment]
Hi, sure, but I think OSM Scout is using vectorial maps and uNav is using tiles map (under openlayers).
Best regards.

**Comment by rinigus** [comment]
Hi! OSM Scout Server has also Mapnik-based rendering into raster tiles as well: https://github.com/rinigus/osmscout-server#raster-tiles . Its actually was built originally with raster tile support that later extended to Mapbox GL vector tiles.

When compared to the online servers, there speed is better if you request larger tiles, as 1024x1024. That way border area handling will not impact as much as in the case of smaller tiles. Other than that as well as not using some small timeout (timeouts on mobile will create issues as device may enter sleep in the middle of the tile generation), there is not that much different from regular servers.

**Comment by costales** [comment]
Hi, thanks for the info and feedback. I will try it soon. A hug!

**Comment by costales** [comment]
WIP :)

**Comment by rinigus** [comment]
Excellent! Good luck with it. Let me know if there are any questions.

Note, that there is also API for geocoding, reverse geocoding, routing. So, tiles are just a part of it.

**Comment by jonnius** [comment]
Make sure to use [OSM Scout Server Full](https://open-store.io/app/osmscout-server-full.jonnius) if you need Mapnik.

**Comment by costales** [comment]
Hi,

uNav is not finding the tiles. 

I installed OSM Scout Server Full and as Profile in the 2nd wizard screen I choosed: `Recommended for raster tiles maps` and in the last one: `Automatic activation`. Then I downloaded a map.

I'm using with this tile URL:

`http://localhost:8553/v1/tile?style=mapnik&daylight=1&z={z}&x={x}&y={y}`

Is that URL OK? Is possible to set a `.png` filename?

Thanks in advance!

**Comment by rinigus** [comment]
Hi,

URL looks fine. On UT, automatic activation doesn't work as you don't use systemd. So you have to run the server in the background and disable suspending the server. Here instructions from open-store:

Preparations:
* Disable app suspension for OSM Scout Server using the UT Tweak Tool: https://open-store.io/app/ut-tweak-tool.sverzegnassi

As for `.png`, I would prefer not to change the API and keep it as it is. modRana, web browsers through leaflet are all fine with such URL. Let's see what will happen when it works in the background.

The server should also display URLs accessed on its window allowing you to debug the connection.

Let me know how it went.

**Comment by costales** [comment]
Thanks for the reply @rinigus 

I disable the app suspension, but no lucky yet.

OSM Scout Server Full sees the requests:

![](https://i.ibb.co/mzgtJyH/screenshot20200729-201314545.png)

but uNav doesn't show the tiles:

![](https://i.ibb.co/bv58fSM/screenshot20200729-201016695.png)

One question: I don't see any button to start the OSM Scout server. Is that right?

Thanks in advance!

**Comment by rinigus** [comment]
As soon as you start the app, it would serve the tiles and all the rest. Try to unzoom for lower z values. Maybe you are in the region without the map data... As for the log on the server, it looks to be getting the requests correctly

**Comment by rinigus** [comment]
Another check is to set `daylight=1` to `daylight=0`. It should change the tile color to darker one, even if there is no data there.

Please also check if server's map manager did download the data. I.e. your region is marked as available.

**Comment by costales** [comment]
Hi,

I did a so simple uNav and did tests.

Leaflet with Carto (works):
https://github.com/costales/unavtest1/blob/master/nav/index.html#L28

Leaflet with OSM Scout (works):
https://github.com/costales/unavtest2/blob/master/nav/index.html#L28

openLayers with Carto (works):
https://github.com/costales/unavtest3/blob/master/nav/index.html#L22

openLayers with OSM Scout (not works):
https://github.com/costales/unavtest4/blob/master/nav/index.html#L22

I think is an issue with openLayers. I will investigate more.

Best regards.

**Comment by rinigus** [comment]
Thanks, great to hear it works with leaflet. I could see it is not loading for me with openlayers either (using https://github.com/rinigus/osmscout-server/blob/master/examples/js/openlayers.html). leaflet, in the same folder, has no issues. strange and don't know why

**Comment by costales** [comment]
Is there a way to invoque the server with a filename .png? (I'm not requesting to change OSM Server, just if it is possible to do that test with the current OSM Server release).

Best regards.

**Comment by rinigus** [comment]
No, unfortunately, it's impossible. API is parsed via HTTP URL and I would have to rewrite request mapper used in the server. All communication with the server is expected to be via HTTP and, for map matching, via DBus. So, we are rather limited with .png extension.

**Comment by rinigus** [comment]
This fixed the server example with openlayers: https://github.com/rinigus/osmscout-server/commit/d2ba707c2b98e137b52660bb47dcfab07c0f188d

Best wishes

PS: getting late over here, will be able to catch up tomorrow

**Comment by costales** [comment]
Hi, I will try it tomorrow. Good night and thank you so much for the
support!

**Comment by rinigus** [comment]
Good luck!

**Comment by costales** [comment]
Hi.

Tiles working as expecting :)))

Thanks a lot!!

**Comment by rinigus** [comment]
Excellent! Next step: geocoder? Nearby search? Router?

**Comment by costales** [comment]
> Excellent! Next step: geocoder? Nearby search? Router?

I want to rewrite uNav first, do it more simple and lighter, it will take me probably 1 or 2 months.

Yes, I'll include everything for offline mode :)))

A hug.

**Comment by costales** [comment]
Hi,

After a lot of tests the raster tiles are so slow for using in uNav. For example, when I do zoom is taking 1 minute to render so much tiles :(

I'm playing then with the vector maps, but with a not complete luck. Could you help me in this please?

For example, the map [[tutorial](https://tegola.io/tutorials/tegola-with-open-layers/)] is [loaded with this code](https://pastebin.ubuntu.com/p/qh26v4QC7s/), but the style is so poor.

![photo_2020-08-03_17-04-59](https://user-images.githubusercontent.com/5886786/89197103-82467180-d5ab-11ea-99ac-d025453a3913.jpg)

I need to apply a nice style (mapbox, osmbright, ...?), but I don't find how to do it with openlayers. I saw that you have a style [here](https://github.com/rinigus/osmscout-server):

`http://localhost:8553/v1/mbgl/style?style=osmbright`

How could I load it in openlayers?

Thanks in advance!!

**Comment by rinigus** [comment]
Will be happy to help. I will check it out on how to apply in openlayers. Let me think how you could reuse as much as possible...

**Comment by costales** [comment]
Thanks a lot!

I was investigating more without luck.

I found [this example](https://codepen.io/ahocevar/pen/xLaBVV) using [olms](https://github.com/openlayers/ol-mapbox-style), but when I run uNav is looks weird:

![image](https://user-images.githubusercontent.com/5886786/89214187-a2cff500-d5c6-11ea-97af-a7d2c7c8c7ed.png)

A hug.

**Comment by rinigus** [comment]
Several comments regarding the change, in no particular order. Note that I don't know much about OpenLayers, take that into account when reading below.

1. Switching to vector styles makes sense. It is way faster as part of rendering job is done while importing data into vector tiles and it is also performed on GPU. As a result, you get faster response. I guess, in our case, you could check performance of Pure Maps on the same hardware and see what to expect with the offline maps. Originally, I was using raster tiles as well. After the test and corresponding switch, I never look back and would recommend it to anyone.

2. When testing Mapnik style, how did you render the tiles? Have you used large tiles, such as 1024x1024, as suggested in OSM Scout Server readme? Are tiles cached once generated by uNav? While caching will not help with the first load, it maybe helpful otherwise... (This was a side note, going back to vector).

3. With vector tiles you can integrate routes and other objects between the layers of the map. That way, Pure Maps puts route under map labels. However, to make it possible, you may have to use Mapbox GL JS or Mapbox GL Native (either official version in Qt 5.9 [tech preview] or unofficial one at https://github.com/rinigus/mapbox-gl-qml). I would recommend the unofficial plugin, but I could be biased. Note that Mapbox GL JS/Native support rendering of raster tiles as well. For example, HERE maps as shown by Pure Maps are using this feature.

4. OSM Scout Server does not know how create raster tiles from vector data, unfortunately. So, we have to use vector tiles directly and cannot go around it by generation of raster tiles.

5. When showing vector maps, you would have to load the style and not vector data directly. Otherwise, you would have to start redoing every rendering step that is made by style usually. So, in this respect, let's focus on style rendering approach and then we have to load data through the style and not access vector tiles directly. I have updated README of the server accordingly.

6. Example at https://openmaptiles.org/docs/website/openlayers/ suggests to use https://github.com/openlayers/ol-mapbox-style, as you did. But notice code at https://github.com/openmaptiles/www.openmaptiles.org/tree/master/maps and that in the example they call `olms` with the style as an argument. 

7. I don't know how good is olms in converting mapbox gl style and whether it is fully supporting all used features. That would come out during experiments, I guess. But there is a risk that you would try to use converter instead of using the original approach developed for these maps (Mapbox GL JS/Native). On the other hand, I presume that full uNav is written using OpenLayers and it is an extra work to move out from it.

I hope that this info is helpful. I will be happy to help further, just ask :) . It would make sense to share as much as we can in these projects and surely switch to vector tiles could only improve that.

**Comment by rinigus** [comment]
What you see in your tests are essentially data that comes from vector tiles. Unfortunately, it is not super simple and you have to consider 2 parts:

- The data layers are imported and distributed as vector tiles. In this case, import layers are described in https://github.com/rinigus/mapbox-gl-importer/tree/master/layers

- Rendering is described by styles. The server is using styles from https://github.com/rinigus/mapbox-gl-styles . Again, we have layers at https://github.com/rinigus/mapbox-gl-styles/tree/master/styles/src/layers combined together into the style as in https://github.com/rinigus/mapbox-gl-styles/tree/master/styles/src/osmbright

To get into it more, I would suggest to read Mapbox GL tutorials and look at their style studio.

**Comment by costales** [comment]
Hi there!


   1.

   Switching to vector styles makes sense. It is way faster as part of
   rendering job is done while importing data into vector tiles and it is also
   performed on GPU. As a result, you get faster response. I guess, in our
   case, you could check performance of Pure Maps on the same hardware and see
   what to expect with the offline maps. Originally, I was using raster tiles
   as well. After the test and corresponding switch, I never look back and
   would recommend it to anyone.

Yes, I tried several times to switch to vector maps, but no results.

   1.

   When testing Mapnik style, how did you render the tiles? Have you used
   large tiles, such as 1024x1024, as suggested in OSM Scout Server readme?
   Are tiles cached once generated by uNav? While caching will not help with
   the first load, it maybe helpful otherwise... (This was a side note, going
   back to vector).

Yes, 1024px. The tiles are not cached in uNav. They are working right, but
not when uNav ask for a query of 30 tiles because the user did a zoom fast.

   1.

   With vector tiles you can integrate routes and other objects between the
   layers of the map. That way, Pure Maps puts route under map labels.
   However, to make it possible, you may have to use Mapbox GL JS or Mapbox GL
   Native (either official version in Qt 5.9 [tech preview] or unofficial one
   at https://github.com/rinigus/mapbox-gl-qml). I would recommend the
   unofficial plugin, but I could be biased. Note that Mapbox GL JS/Native
   support rendering of raster tiles as well. For example, HERE maps as shown
   by Pure Maps are using this feature.

Yes, but in uNav everything is using openlayers and switch to other library
would be tedious.

   1.

   OSM Scout Server does not know how create raster tiles from vector data,
   unfortunately. So, we have to use vector tiles directly and cannot go
   around it by generation of raster tiles.

One question, the OSM Scout Server is using MVT format?

   1.

   When showing vector maps, you would have to load the style and not
   vector data directly. Otherwise, you would have to start redoing every
   rendering step that is made by style usually. So, in this respect, let's
   focus on style rendering approach and then we have to load data through the
   style and not access vector tiles directly. I have updated the README of
   the server accordingly.

openLayers is complex, but in all examples I saw they declare the vector
tiles and then a style. I think is openlayers who deal with that, but I'm
not sure.

   1.

   Example at https://openmaptiles.org/docs/website/openlayers/ suggests to
   use https://github.com/openlayers/ol-mapbox-style, as you did. But
   notice code at
   https://github.com/openmaptiles/www.openmaptiles.org/tree/master/maps
   and that in the example they call olms with the style as an argument.
   2.

   I don't know how good is olms in converting mapbox gl style and whether
   it is fully supporting all used features. That would come out during
   experiments, I guess. But there is a risk that you would try to use
   converter instead of using the original approach developed for these maps
   (Mapbox GL JS/Native). On the other hand, I presume that full uNav is
   written using OpenLayers and it is an extra work to move out from it.

Yes, use mapbox would be a last option. openLayers is the most powerful map
library I ever saw, there has to be a way to do this.


I need to invert time in other features, if not, I can't progress in the
new release. I'll come back to this trying to do it working.

A hug and thank you so much :)

**Comment by rinigus** [comment]
I understand that switching away from OpenLayers would be a major effort. It took me some time to switch Poor Maps (older name at that time) from raster to vector, so I know exactly what is involved in it.

Replies to your questions: 

1. Yes, OSM Scout Server does use MVT format. That's why you were able to render the coastlines and such above.

2. Maybe OpenLayers can reuse Mapbox GL style. It is surely worth to test.

Good luck with the new release and this part can surely wait...

**Comment by costales** [comment]
Finally I got it, using olms! You were right, I have to use only the style
URL and not the tiles.

uNav 3 will be released with your vector maps for offline use! :)))

Another question more please, do you know an online services same as OSM
Server for routes and search? I am asking it for do the same code for
online & offline responses from the APIs.

Thank you!

**Comment by rinigus** [comment]
Excellent news - congratulations!

Re search: no, unfortunately the search engine I wrote myself and it has an API that was designed for it.

Re routing: I am using Stadia Maps https://stadiamaps.com by default as they are using the same routing engine as OSM Scout Server: Valhalla. Free tier gives 2500 requests per day which was so far sufficient. Valhalla project at https://github.com/valhalla/valhalla, API described in docs at https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md

Best wishes!

**Comment by jonnius** [comment]
Just for the record: does that mean unav3 won't need OSM Scout Server with Mapnik? In that case I would unpublish it from the OpenStore.

**Comment by costales** [comment]
Hi!

It means that uNav will use OSM Scout Server Slim, not the Full. But,
please, wait a few weeks, I need to finish the release and test it a lot
with these maps.

Thanks to all of you! A hug!

**Comment by costales** [comment]
Please @jonnius if you can, remove the Full version from the store if you want.
Thanks a lot!

**Comment by jonnius** [comment]
Ok. Looking forward to the uNav release with Offline navigation!

**Comment by costales** [comment]
Thanks :) I'm with the ~50% complete... I am looking too xD

Thanks to all of you for OSM Scout Server! A hug!

**Comment by rinigus** [comment]
Looking forward, Great that you work on it!

**Comment by costales** [comment]
Hi @rinigus 

Is a way to do reverse geocoding? For a latitude & longitude returns the place name.

Thanks in advance.

**Comment by rinigus** [comment]
@costales , sure, there is reverse geocoder: https://github.com/rinigus/osmscout-server#poi-search-near-a-reference-position-or-route

For list of possible POI types, request as in https://github.com/rinigus/osmscout-server#list-of-available-poi-types

Note that the reverse geocoder can also find POIs along the route. As for example, when you drive, show me the cafe within 200 meters from the route starting from current location. Handy on long trips!

**Comment by costales** [comment]
Hi,

But I don't need POIs in this case :) I would need for example, the
name of the street of those coordinates.

For example: http://photon.komoot.de/reverse?lon=10&lat=52 would give
for that lon & lat the name of "Geographischer Punkt".

How would be the URL in OSM Scout for returning that? Something like this one?

http://localhost:8553/v1/guide?limit=1&lng={lng}&lat={lat}

Thanks!

**Comment by rinigus** [comment]
Streets are tricky, it may not find them. But the houses with numbers/names are also considered as POIs. Default values are given in https://github.com/rinigus/osmscout-server/blob/master/src/requestmapper.cpp#L723 . So, without radius specified, it will be 100 meters. 

In Pure Maps, I am exactly using this way to find the objects when user is long tapping on the screen. However, I specify radius depending on map zoom as it would be roughly when covering it by a finger.

As for streets, it is tricky as all objects are stored as points in the geocoder. So, while streets are there, it does not have full polyline. Thus, if you tap on a street, but not next to the stored point, you will miss it. Its mainly for storage reasons and avoiding to have larger databases.

**Comment by costales** [comment]
Hi,

If it doesn't return anything, it's OK.

Then, using this
http://localhost:8553/v1/guide?limit=1&lng={lng}&lat={lat} would be
the right way? With limit=1 would give the nearest? Any other URL
compose for better information about the user click on map and give
him the name of that point?

Thanks!

**Comment by costales** [comment]
Hi,

With this URL
http://localhost:8553/v1/guide?limit=1&lng=-5.668974148516006&lat=43.53230762045101
I'm getting in the OSM Scout log:

*Request:
/v1/guide?limit=1&lng=-5.668974148516006&lat=43.53230762045101 Error while
reading guide query parameters*

**Comment by rinigus** [comment]
Just checked, you have to use slightly different:

http://localhost:8553/v1/guide??radius=XXXX&limit=1&lng=XXXX&lat=XXXXX&poitype=any

as you see, poitype has to be specified as well

**Comment by rinigus** [comment]
PS: note that radius is not obligatory

**Comment by rinigus** [comment]
PPS: you need to specify either poitype or name (or both). hence the placeholder `any`

**Comment by costales** [comment]
Hi,

I'm so sorry, but it's not working for me. I tried from the shell for know
what is happening:

wget
http://localhost:8553/v1/guide?limit=1&lng=-5.668974&lat=43.532307&poitype=any
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8553... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8553... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-08-12 23:12:00 ERROR 400: Bad Request.

Appears the server is not working, but it gives tiles and searches...

**Comment by costales** [comment]
From `clickable logs` I'm getting:

qml: [JS] (file:///opt/
click.ubuntu.com/navigator.costales/3.0/nav/index.html:0) Access to
XMLHttpRequest at '
http://localhost:8553/v1/guide?limit=10&lng=-6.598679253710262&lat=43.77830779959967&poitype=any'
from origin 'file://' has been blocked by CORS policy: No
'Access-Control-Allow-Origin' header is present on the requested resource.

Any idea?

**Comment by rinigus** [comment]
Re wget example: are you sure you don't need to enclose URL in ''? When testing on PC, it works (small JSON returned)

Re clickable logs: no idea, sorry, as I don't know enough about UT clickable.

Let's try to get it to work with terminal. Please test search from terminal as well, maybe server got suspended by UT?

**Comment by costales** [comment]
Hi,

Yes, wget needed the quotes, with that worked :)

I tried ajax and XMLHttpRequest for getting the data and it's not
working because of CORS policy:

qml: [JS] (file:///opt/click.ubuntu.com/navigator.costales/3.0/nav/index.html:0)
Access to XMLHttpRequest at 'http://localhost:8553/v1/guide' from
origin 'file://' has been blocked by CORS policy: No
'Access-Control-Allow-Origin' header is present on the requested
resource.

It's a bit weird, because it's localhost.  Is the server returning a
header like this?

Access-Control-Allow-Origin: *

Thanks in advance

**Comment by rinigus** [comment]
TBH, I don't remember. I would expect it to return the same headers as the search does. Is it possible to somehow check it?

**Comment by costales** [comment]
I think is not returning that:

```
phablet@ubuntu-phablet:~$ wget -S -O - "http://localhost:8553/v1/guide?limit=1&lng=-5.668974&lat=43.532307&poitype=any"
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8553... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8553... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Content-Type: application/json; charset=UTF-8
  Date: Wed, 12 Aug 2020 22:05:32 GMT
Length: unspecified [application/json]
Saving to: ‘STDOUT’

-                       [<=>                 ]       0  --.-KB/s               {
    "origin": {
        "lat": 43.532307,
        "lng": -5.668974
    },
    "query_name": "",
    "query_type": "any",
    "results": [
    ]
}
-                       [ <=>                ]     148  --.-KB/s    in 0s      

2020-08-13 00:05:32 (2.93 MB/s) - written to stdout [148]

phablet@ubuntu-phablet:~$
```

From QML worked fine, but from javascript is not working. I'm trying to fix that, but I'm not sure if it's possible from the client side...

**Comment by rinigus** [comment]
Could be. But what's the difference with search then? Do you call search from QML and guide from JS?

**Comment by rinigus** [comment]
PS: If the header is needed, I will make the corresponding patch and the new release. Just want to be sure.

**Comment by costales** [comment]
Yes, the search is from QML (works) and everything else, from JS (doesn't work). I think is because JS is in a container of QML and works different :+1: 

I was testing for example photon:

```
phablet@ubuntu-phablet:~$ wget -S -O - "http://photon.komoot.de/api/?q=xixon"
Resolving photon.komoot.de (photon.komoot.de)... 88.198.70.11
Connecting to photon.komoot.de (photon.komoot.de)|88.198.70.11|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: nginx/1.9.3 (Ubuntu)
  Date: Wed, 12 Aug 2020 18:26:57 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Access-Control-Allow-Origin: *
  Access-Control-Request-Method: get
  Access-Control-Allow-Headers: *
Length: unspecified [application/json]
Saving to: ‘STDOUT’

-                       [<=>                 ]       0  --.-KB/s               {"features":[{"geometry":{"coordinates":[-5.6626443,43.5450394],"type":"Point"},"type":"Feature","properties":{"osm_id":345576,"osm_type":"R","extent":[-5.8213224,43.5867678,-5.5631197,43.4415087],"country":"Spain","osm_key":"place","osm_value":"city","name":"Gijón","state":"Asturias"}},{"geometry":{"coordinates":[-8.542050302904453,42.88791585],"type":"Point"},"type":"Feature","properties":{"osm_id":78595257,"osm_type":"W","extent":[-8.542558,42.8886474,-8.5409432,42.8871254],"country":"Spain","osm_key":"leisure","city":"Santiago de Compostela","osm_value":"park","postcode":"15705","name":"Parque de Xixón","state":"Galicia"}},{"geometry":{"coordinates":[-8.542681965562565,42.8877848],"type":"Point"},"type":"Feature","properties":{"osm_id":99618114,"osm_type":"W","extent":[-8.5442828,42.888901,-8.5424272,42.886661],"country":"Spain","osm_key":"leisure","city":"Santiago de Compostela","osm_value":"park","postcode":"15705","name":"Parque de Xixón","state":"Galicia"}},{"geometry":{"coordinates":[-5.779342,43.2530959],"type":"Point"},"type":"Feature","properties":{"osm_id":179043546,"osm_type":"W","extent":[-5.7795691,43.2547226,-5.7792186,43.2513465],"country":"Spain","osm_key":"highway","city":"Mieres","osm_value":"residential","postcode":"33600","name":"Cai Xixón","state":"Asturias"}},{"geometry":{"coordinates":[-5.721318,43.5394427],"type":"Point"},"type":"Feature","properties":{"osm_id":4275322,"osm_type":"W","extent":[-5.7223557,43.5403093,-5.7208346,43.5382755],"country":"Spain","osm_key":"highway","city":"Gijón","osm_value":"trunk","postcode":"33691","name":"Accesu sentíu Xixón","state":"Asturias"}},{"geometry":{"coordinates":[-5.7188076,43.5351738],"type":"Point"},"type":"Feature","properties":{"osm_id":96565710,"osm_type":"W","extent":[-5.7192098,43.5355547,-5.7184225,43.5351738],"country":"Spain","osm_key":"highway","city":"Gijón","osm_value":"trunk","postcode":"33691","name":"Carretera Xixón-Avilés","state":"Asturias"}},{"geometry":{"coordinates":[-5.7077637,43.5294113],"type":"Point"},"type":"Feature","properties":{"osm_id":4307239,"osm_type":"W","extent":[-5.7079903,43.5295232,-5.7076042,43.5292318],"country":"Spain","osm_key":"highway","city":"Gijón","osm_value":"trunk","postcode":"33311","name":"Carretera Xixón-Avilés","state":"Asturias"}},{"geometry":{"coordinates":[-5.718618,43.5357617],"type":"Point"},"type":"Feature","properties":{"osm_id":321567182,"osm_type":"W","extent":[-5.7187031,43.5358456,-5.7183663,43.5357352],"country":"Spain","osm_key":"highway","city":"Gijón","osm_value":"tertiary","postcode":"33691","name":"Entrada Xixón oeste","state":"Asturias"}},{"geometry":{"coordinates":[-5.7212214,43.5394718],"type":"Point"},"type":"Feature","properties":{"osm_id":339200510,"osm_type":"W","extent":[-5.7220409,43.5403267,-5.7208652,43.5385021],"country":"Spain","osm_key":"highway","city":"Gijón","osm_value":"trunk","postcode":"33691","name":"Carretera Xix-                       [ <=>                ]   2.93K  --.-KB/s    in 0s      

2020-08-13 00:33:49 (30.0 MB/s) - written to stdout [3003]

phablet@ubuntu-phablet:~$ 
```

The header is really important trying to get data from JS:

```
  Access-Control-Allow-Origin: *
  Access-Control-Request-Method: get
  Access-Control-Allow-Headers: *
```

As OSM Scout Server doesn't return those parameters, any JS application will be rejected because of CORS origin :/

Would be possible to include those parameters in the header of the reply of the server as test?

Thanks in advance.

**Comment by costales** [comment]
I think it was fixed adding this into the QML! :))))

`settings.localContentCanAccessRemoteUrls: true`

But I'm always getting an empty value:

`{"origin":{"lat":43.53662234550157,"lng":-5.66564692509271},"query_name":"","query_type":"any","results":[]}`

This is the call:

```
wget -qO- "http://localhost:8553/v1/guide?limit=1&lng=-5.668974&lat=43.532307&poitype=any"

{
    "origin": {
        "lat": 43.532307,
        "lng": -5.668974
    },
    "query_name": "",
    "query_type": "any",
    "results": [
    ]
}
```

And it's a city, in 100 meters, it should be there any POI.

Am I calling it right?

Thanks

**Comment by rinigus** [comment]
Try to increase the radius. Let's see if it helps

**Comment by costales** [comment]
> Try to increase the radius. Let's see if it helps

Same with 1km:

`http://localhost:8553/v1/guide?limit=10&radius=1000&lng=-5.668974&lat=43.532307&poitype=any`

The reply is:

```
    "origin": {
        "lat": 43.532307,
        "lng": -5.668974
    },
    "query_name": "",
    "query_type": "any",
    "results": [
    ]
}
```

**Comment by rinigus** [comment]
Hmm, let me see if I can reproduce it

**Comment by rinigus** [comment]
After downloading Spain, I am getting

```
curl "http://localhost:8553/v1/guide?limit=1&radius=100&lng=-5.668974&lat=43.532307&poitype=any" 
```

```JSON
{
    "origin": {
        "lat": 43.532307,
        "lng": -5.668974
    },
    "query_name": "",
    "query_type": "any",
    "results": [
        {
            "admin_levels": 4,
            "admin_region": "Aparcamiento reservado para motos, Gijón/Xixón, Asturias / Asturies, Asturias / Asturies",
            "distance": 23.09495124324293,
            "lat": 43.53251213977123,
            "lng": -5.669021797694427,
            "object_id": 91835,
            "phone": "",
            "postal_code": "",
            "title": "Aparcamiento reservado para motos, Gijón/Xixón",
            "type": "Motorcycle parking",
            "website": ""
        }
    ]
}
```

**Comment by costales** [comment]
Thanks a lot for the test.

I tried in my another phone with UT and it worked! In my 1st phone it
doesn't work, with same maps and profile in both of them. Weird...

One thing less :)

A hug!

**Comment by rinigus** [comment]
I wonder if the maps are the same... Maybe just would need to check for updates, maybe re-download and ensure it is not Barcelona, but full Spain

**Comment by costales** [comment]
Yes, it was weird. Maps & search worked but not the POIs.

I flashed my device and it is working fine now. Both of my phones.

**Comment by costales** [comment]
Hi,

About the POIs, there are 2 types of them that are not getting me anything (other yes, there are getting data).

They are `building_church` and `amenity_taxi`. When I search my city (Xixón) nothing comes up.

Testing here, I can see POIs  http://openpoimap.org/

![image](https://user-images.githubusercontent.com/5886786/90252068-2a2b2d00-de3f-11ea-8f7b-4b7b47aa1604.png)

 
I think OSM Scout should return POIs (the URL is the same as any other POI working). Any idea please? Thanks!

**Comment by costales** [comment]
API call examples:

Doesn't work:
wget "http://localhost:8553/v1/guide?radius=1000&limit=100&lng=-5.66355&lat=43.53654&poitype=amenity_taxi"

Works:
wget "http://localhost:8553/v1/guide?radius=1000&limit=100&lng=-5.66355&lat=43.53654&poitype=amenity_fuel"

**Comment by rinigus** [comment]
Question is whether I import those POIs. Not all is getting into the
database, I have to select them. Although, they seem to be there in
https://github.com/rinigus/geocoder-nlp/blob/master/importer/stylesheet/whitelist
.
I will have to check

**Comment by rinigus** [comment]
For churches, use `amenity_place_of_worship` - then it will find all fine. 

As for taxi, it did not import for some reason. And it is not very clear to me why it happened. Will have to look into it when I get a chance to work on the import again

Alternative, is to use one of the aliases as returned by http://localhost:8553/v1/poi_types, but those would depend on used language. And as taxi is not in the database, it will not help there

**Comment by costales** [comment]
Thanks @rinigus 

`amenity_place_of_worship` worked perfect.


Another option for a Taxi didn't work:

```
phablet@ubuntu-phablet:~$ cat poi_types  | grep -i taxi
    "Taxi",
    "Taxi Rank",
    "Taxi Ranks",
    "Taxis",
phablet@ubuntu-phablet:~$
```

A hug.

**Comment by rinigus** [comment]
No, data is not imported from OSM, unfortunately. But let's keep it in mind when I get back to geocoder import - there are few other things to fix as well.

Opened an issue regarding it in OSM Scout Server repo

**Comment by costales** [comment]
Hi @rinigus 

With georeverse I saw things like these:

The title has ` " , "` at the start: `"title":" , Gijón/Xixón"` and it looks weird:

`{"origin":{"lat":43.52922728792814,"lng":-5.660495253388129},"query_name":"","query_type":"any","results":[{"admin_levels":4,"admin_region":" , Gijón/Xixón, Asturias / Asturies, Asturias / Asturies","distance":4.222268129033717,"lat":43.52920095271767,"lng":-5.660457504246068,"object_id":91984,"phone":"","postal_code":"","title":" , Gijón/Xixón","type":"Motorcycle parking","website":""}]}`

The number of street is before the name, probably English format but I would like to rise you if it is not the desired result:

`{"origin":{"lat":43.53336587445253,"lng":-5.658108328263222},"query_name":"","query_type":"any","results":[{"admin_levels":6,"admin_region":"9, Calle San Rafael, Distrito Este, Gijón/Xixón, Asturias / Asturies, Asturias / Asturies","distance":5.769474675495295,"lat":43.53341336200694,"lng":-5.658137393430906,"object_id":95178,"phone":"","postal_code":"33209","title":"9, Calle San Rafael","type":"address","website":""}]}`

Thanks!

**Comment by rinigus** [comment]
Evening @costales,

what you observe, is due to the format and notation used by the geocoder. In short, cannot change it unless major rework will be done on it. Below, is why

In the geocoder, I am storing each object (as house) with the link to its parent object (as street). Geocoder later creates an address `admin_region` as a string representation of a hierarchy. So, in the second example, you get exactly as it is in OSM: house number, street, district, ..., county boundary, state boundary (last ones are with the same name). 

In the first example, we have a POI without a name. Hence it starts with " " as a name and proceeds after that. As a result, you get title with " , " in the beginning. Not optimal, for sure, but allows to distinguish POI from the region with that name. Should think how to show it differently...

At this stage, I don't save what is the level the object belongs to. So, I don't know that 9 is a house number and Calle San Rafael is a street. When I get to the geocoder, should think how to approach it better.

**Comment by costales** [comment]
Hi,

OK :) No problem, I'll patch the name.

Thanks for the feedback!

**Comment by costales** [comment]
Hi, in my tests, the drinking wather POIs are not found either (`amenity_drinking_water`).

Thanks in advance!

**Comment by rinigus** [comment]
I presume it is not imported as it is not in https://github.com/rinigus/geocoder-nlp/blob/master/importer/stylesheet/whitelist

**Comment by costales** [comment]
But the tags here are valid too? Should they find POIs?
Or should I use only your link as tags resource?

https://rinigus.github.io/osmscout-server/tags/tag2alias_en.html

Thanks in advance!
-- 
Sent using Dekko from my Ubuntu device


-- 
--
Costales.

**Comment by rinigus** [comment]
tags are valid. The list I referred to has POI types which are imported even without names. The notation of the tags in this list is can be different from the one used by server, it is notation of the lib I am using for import. The tag list you refer to is used while searching via OSM Scout Server. Sorry for complexity, project has been evolving for years and that shows.

**Comment by costales** [comment]
Sorry, but then, drinking water should be find when I ask for that amenity?

-- 
Sent using Dekko from my Ubuntu device

**Comment by rinigus** [comment]
No, it is not in the database. It was ignored by the import script, even with the names

**Comment by costales** [comment]
Released! :) Thanks a lot @rinigus and @jonnius for your support and help!!

**Comment by rinigus** [comment]
Congratulations!!!
